- type: job
  id: HeadOperations
  name: job-name-headoperations
  description: job-description-headoperations
  playTimeTracker: JobHeadOperations
  requirements:
    - !type:DepartmentTimeRequirement
      department: AlphaGarrison
      time: 0
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: HeadOperationsGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - Capital_Operation

- type: startingGear
  id: HeadOperationsGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: HeadOperationsIDCard
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
