- type: job
  id: StaffOfficer
  name: job-name-staffofficer
  description: job-description-staffofficer
  playTimeTracker: JobStaffOfficer
  startingGear: StaffOfficerGear
  icon: "JobIconStaffOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - HeadOperations

- type: startingGear
  id: StaffOfficerGear
  equipment:
    neck: ClothingNeckHeadphones
    gloves: ClothingHandsGlovesMarine
    jumpsuit: ClothingUniformJumpsuitStaffOfficer
    eyes: ClothingEyesGlassesRPG
    id: StaffOfficerIDCard
    ears: ClothingHeadsetMarineCommands
    belt: ClothingBeltAssault
    shoes: ClothingShoesCentcomBlack
