- type: job
  id: ChiefShipsEngineer
  name: job-name-chiefshipsengineer
  description: job-description-chiefshipsengineer
  playTimeTracker: JobChiefShipsEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: ChiefShipsEngineerGear
  icon: "JobIconChiefShipsEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance

- type: startingGear
  id: ChiefShipsEngineerGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: ChiefShipsEngineerIDCard
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
