- type: job
  id: ChiefShipsEngineer
  name: job-name-chiefshipsengineer
  description: job-supervisors-staff-officer
  playTimeTracker: JobChiefShipsEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: ChiefShipsEngineerGear
  icon: "JobIconChiefShipsEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance
    - Atmospherics
    - Engineering
    - Command
    - ChiefEngineer

- type: startingGear
  id: ChiefShipsEngineerGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackChiefEngineerFilled
    shoes: ClothingShoesColorBrown
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
    id: ChiefShipsEngineerIDCard