- type: job
  id: ShipsEngineer
  name: job-name-shipsengineer
  description: job-description-shipsengineer
  playTimeTracker: JobShipsEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: ShipsEngineerGear
  icon: "JobIconShipsEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance
    - Atmospherics
    - Engineering

- type: startingGear
  id: ShipsEngineerGear
  equipment:
    head: ClothingHeadHatHardhatYellow
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    id: ShipsEngineerIDCard