- type: job
  id: MilitaryScientist
  name: job-name-militaryscientist
  description: job-description-militaryscientist
  playTimeTracker: JobMilitaryScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: AlphaGarrison
      time: 0
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: MilitaryScientistGear
  icon: "JobIconMilitaryScientist"
  supervisors: job-supervisors-cmofficer
  canBeAntag: false
  access:
    - Research

- type: startingGear
  id: MilitaryScientistGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: MilitaryScientistIDCard
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
