- type: job
  id: DeltaMarine
  name: job-name-delta-marine
  description: job-description-deltamarine
  playTimeTracker: JobDeltaMarine
  requirements:
    - !type:DepartmentTimeRequirement
      department: DeltaGarrison
      time: 0
  startingGear: DeltaMarineGear
  icon: "JobIconDeltaMarine"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - TGMSD

- type: startingGear
  id: DeltaMarineGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
