- type: job
  id: AlfaEngineer
  name: job-name-alfa-engineer
  description: job-description-alfaengineer
  playTimeTracker: JobAlfaEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: AlphaGarrison
      time: 0
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: AlfaEngineerGear
  icon: "JobIconAlfaEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - TGMSAE

- type: startingGear
  id: AlfaEngineerGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
