- type: job
  id: AlfaMedic
  name: job-name-alfa-medic
  description: job-description-alfamedic
  playTimeTracker: JobAlfaMedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: AlphaGarrison
      time: 0
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: AlfaMedicGear
  icon: "JobIconAlfaMedic"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
    - TGMSAM

- type: startingGear
  id: AlfaMedicGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: AMedicIDCard
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
