- type: job
  id: MilitaryPoliceman
  name: job-name-militarypoliceman
  description: job-description-militarypoliceman
  playTimeTracker: JobMilitaryPoliceman
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: MilitaryPolicemanGear
  icon: "JobIconMilitaryPoliceman"
  supervisors: job-supervisors-police-officer
  canBeAntag: false
  accessGroups:
    - MilitaryPoliceman

- type: startingGear
  id: MilitaryPolicemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryPolice
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetBasic
    outerClothing: ClothingOuterVestArmorSec # Corvax-Resprite
    id: PolicemanIDCard
    ears: ClothingHeadsetSecurity
