- type: job
  id: MilitaryPoliceOfficer
  name: job-name-militarypoliceofficer
  description: job-description-militarypoliceofficer
  playTimeTracker: JobMilitaryPoliceOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: MilitaryPoliceOfficerGear
  icon: "JobIconMilitaryPoliceOfficer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Maintenance

- type: startingGear
  id: MilitaryPoliceOfficerGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
