- type: job
  id: DeltaMarine
  name: job-name-delta-marine
  description: job-description-deltamarine
  playTimeTracker: JobDeltaMarine
  startingGear: DeltaMarineGear
  icon: "JobIconDeltaMarine"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadDelta

- type: startingGear
  id: DeltaMarineGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitdelta_mar
    id: DRiflemanIDCard
    ears: ClothingHeadsetMarineDelta
