- type: department
  id: CommandersGarrisons
  description: department-CommandersGarrisons-description
  color: "#B22222"
  roles:
    - AlfaCommander
    - DeltaCommander
    - BravoCommander
    - CharlieCommander

- type: department
  id: SpecialistsGarrison
  description: department-SpecialistsGarrison-description
  color: "#1E90FF"
  roles:
    - AlfaSpecialist
    - DeltaSpecialist
    - BravoSpecialist
    - CharlieSpecialist

- type: department
  id: MedicsGarrison
  description: department-MedicsGarrison-description
  color: "#FFD700"
  roles:
    - AlfaMedic
    - DeltaMedic
    - BravoMedic
    - CharlieMedic

- type: department
  id: EngineersGarrison
  description: department-EngineersGarrison-description
  color: "#FFD700"
  roles:
    - AlfaEngineer
    - DeltaEngineer
    - BravoEngineer
    - CharlieEngineer

- type: department
  id: MarinesGarrison
  description: department-MarinesGarrison-description
  color: "#8A2BE2"
  roles:
    - AlfaMarine
    - DeltaMarine
    - BravoMarine
    - CharlieMarine

- type: department
  id: MilitaryPolice
  description: department-MilitaryPolice-description
  color: "#DC143C"
  roles:
    - MilitaryPoliceman
    - MilitaryPoliceOfficer

- type: department
  id: MilitaryScientist
  description: department-MilitaryScientist-description
  color: "#C71585"
  roles:
    - MilitaryScientist

- type: department
  id: LogisticsSupport
  description: department-LogisticsSupport-description
  color: "#FF8C00"
  roles:
    - SupplyOfficer
    - Rigger

- type: department
  id: MedicalUnit
  description: department-MedicalUnit-description
  color: "#20B2AA"
  roles:
    - MilitaryMedic
    - MilitaryMainMedic

- type: department
  id: ConstructionBattalion
  description: department-ConstructionBattalion-description
  color: "#F0E68C"
  roles:
    - ChiefShipsEngineer
    - ShipsEngineer

- type: department
  id: Command
  description: department-Command-description
  color: "#7FFFD4"
  roles:
    - HeadOperations
    - FieldCommander
    - StaffOfficer

- type: department
  id: Pilots
  description: department-Pilots-description
  color: "#7FFFD4"
  roles:
    - PilotNormandy
    - PilotRaptor

- type: department
  id: Xeno
  description: department-Xeno-description
  color: "#4B0082"
  roles:
    - Kseno
    - Pretor
    - Quinn
    - Runi
