- type: department
  id: AlphaGarrison
  description: department-AlphaGarrison-description
  color: "#B22222"
  roles:
    - AlfaMarine
    - AlfaMedic
    - AlfaEngineer
    - AlfaCommander
    - AlfaSpecialist

- type: department
  id: DeltaGarrison
  description: department-AlphaGarrison-description
  color: "#1E90FF"
  roles:
    - DeltaMarine
    - DeltaMedic
    - DeltaEngineer
    - DeltaCommander
    - DeltaSpecialist

- type: department
  id: BravoGarrison
  description: department-AlphaGarrison-description
  color: "#FFD700"
  roles:
    - BravoMarine
    - BravoMedic
    - BravoEngineer
    - BravoCommander
    - BravoSpecialist

- type: department
  id: CharlieGarrison
  description: department-AlphaGarrison-description
  color: "#8A2BE2"
  roles:
    - CharlieMarine
    - CharlieMedic
    - CharlieEngineer
    - CharlieCommander
    - CharlieSpecialist

- type: department
  id: MilitaryPolice
  description: department-MilitaryPolice-description
  color: "#DC143C"
  roles:
    - MilitaryPoliceman
    - MilitaryPoliceOfficer

- type: department
  id: MilitaryScientist
  description: department-MilitaryScientist-description
  color: "#C71585"
  roles:
    - MilitaryScientist

- type: department
  id: LogisticsSupport
  description: department-LogisticsSupport-description
  color: "#FF8C00"
  roles:
    - SupplyOfficer
    - Rigger

- type: department
  id: MedicalUnit
  description: department-MedicalUnit-description
  color: "#20B2AA"
  roles:
    - MilitaryMedic
    - MilitaryMainMedic

- type: department
  id: ConstructionBattalion
  description: department-ConstructionBattalion-description
  color: "#F0E68C"
  roles:
    - ChiefShipsEngineer
    - ShipsEngineer

- type: department
  id: Command
  description: department-Command-description
  color: "#7FFFD4"
  roles:
    - HeadOperations
    - FieldCommander
    - StaffOfficer
    - PilotOfficer

- type: department
  id: Xeno
  description: department-Xeno-description
  color: "#4B0082"
  roles:
    - Kseno
    - Pretor
    - Quinn
    - Runi
