- type: job
  id: BravoSpecialist
  name: job-name-bravo-specialist
  description: job-description-bravospecialist
  playTimeTracker: JobBravoSpecialist
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: BravoSpecialistGear
  icon: "JobIconBravoSpecialist"
  supervisors: job-supervisors-commander
  canBeAntag: false
  access:
    - SquadBravo
    - SquadSpecialist

- type: startingGear
  id: BravoSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitbravo_spec
    id: BSpecialistsIDCard
    ears: ClothingHeadsetMarineBravo
