- type: job
  id: PilotRaptor
  name: job-name-pilotraptor
  description: job-description-pilotraptor
  playTimeTracker: JobPilotRaptor
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: PilotOfficerGear
  icon: "JobIconPilotRaptor"
  supervisors: job-supervisors-staff-officer
  canBeAntag: false
  access:
    - Command
    - Pilot
    - PilotRaptor
    - Maintenance

- type: startingGear
  id: PilotOfficerGear
  equipment:
    head: ClothingHeadHelmetMarine
    jumpsuit: ClothingUniformJumpsuitMarine
    back: ClothingBackpackMarine
    shoes: ClothingShoesBootsCombat
    eyes: ClothingEyesGlassesRPG
    id: PilotRaptorIDCard
    ears: ClothingHeadsetPilotShattle
