# Overall play time, across all roles.
# This tracker must exist, it is used directly by PlayTimeTrackingManager
- type: playTimeTracker
  id: Overall

# Jobs
# - type: playTimeTracker
  # id: JobAtmosphericTechnician

# - type: playTimeTracker
  # id: JobBartender

- type: playTimeTracker # Used as a tracker for all borgs and midround borging.
  id: JobBorg

# - type: playTimeTracker
  # id: JobBotanist

# - type: playTimeTracker
  # id: JobCaptain
# ShipsEngineer --------------------------
- type: playTimeTracker
  id: JobChiefShipsEngineer

- type: playTimeTracker
  id: JobShipsEngineer
# Marine tracker -------------------------
- type: playTimeTracker
  id: JobAlfaMarine

- type: playTimeTracker
  id: JobDeltaMarine

- type: playTimeTracker
  id: JobBravoMarine

- type: playTimeTracker
  id: JobCharlieMarine
# Medic tracker ---------------------------
- type: playTimeTracker
  id: JobAlfaMedic

- type: playTimeTracker
  id: JobDeltaMedic

- type: playTimeTracker
  id: JobBravoMedic

- type: playTimeTracker
  id: JobCharlieMedic
# Engineer tracker -------------------------
- type: playTimeTracker
  id: JobAlfaEngineer

- type: playTimeTracker
  id: JobDeltaEngineer

- type: playTimeTracker
  id: JobBravoEngineer

- type: playTimeTracker
  id: JobCharlieEngineer
# Commander tracker -------------------------
- type: playTimeTracker
  id: JobAlfaCommander

- type: playTimeTracker
  id: JobDeltaCommander

- type: playTimeTracker
  id: JobBravoCommander

- type: playTimeTracker
  id: JobCharlieCommander
# Specialist tracker ------------------------
- type: playTimeTracker
  id: JobAlfaSpecialist

- type: playTimeTracker
  id: JobDeltaSpecialist

- type: playTimeTracker
  id: JobBravoSpecialist

- type: playTimeTracker
  id: JobCharlieSpecialist
# Military Police ----------------------------
- type: playTimeTracker
  id: JobMilitaryPoliceman

- type: playTimeTracker
  id: JobMilitaryPoliceOfficer
# MilitaryScientist ---------------------------
- type: playTimeTracker
  id: JobMilitaryScientist
# Cargo ---------------------------------------
- type: playTimeTracker
  id: JobSupplyOfficer

- type: playTimeTracker
  id: JobRigger
# Medic ---------------------------------------
- type: playTimeTracker
  id: JobMilitaryMedic

- type: playTimeTracker
  id: JobMilitaryMainMedic
# Command -------------------------------------
- type: playTimeTracker
  id: JobHeadOperations

- type: playTimeTracker
  id: JobFieldCommander

- type: playTimeTracker
  id: JobStaffOfficer
# Pilots --------------------------------------
- type: playTimeTracker
  id: JobPilotRaptor

- type: playTimeTracker
  id: JobPilotMech

- type: playTimeTracker
  id: JobPilotNormandy
# Xeno ----------------------------------------
- type: playTimeTracker
  id: JobKseno

- type: playTimeTracker
  id: JobRuni

- type: playTimeTracker
  id: JobQuinn

- type: playTimeTracker
  id: JobPretor

- type: playTimeTracker
  id: JobCrusher
#----------------------------------------------
# - type: playTimeTracker
  # id: JobCargoTechnician

# - type: playTimeTracker
  # id: JobCentralCommandOfficial

# - type: playTimeTracker
  # id: JobChaplain

# - type: playTimeTracker
  # id: JobChef

# - type: playTimeTracker
  # id: JobChemist

# - type: playTimeTracker
  # id: JobChiefEngineer

# - type: playTimeTracker
  # id: JobChiefMedicalOfficer

# - type: playTimeTracker
  # id: JobClown

# - type: playTimeTracker
  # id: JobDetective

# - type: playTimeTracker
  # id: JobERTEngineer

# - type: playTimeTracker
  # id: JobERTJanitor

# - type: playTimeTracker
  # id: JobERTLeader

# - type: playTimeTracker
  # id: JobERTMedical

# - type: playTimeTracker
  # id: JobERTSecurity

# - type: playTimeTracker
  # id: JobHeadOfPersonnel

# - type: playTimeTracker
  # id: JobHeadOfSecurity

# - type: playTimeTracker
  # id: JobJanitor

# - type: playTimeTracker
  # id: JobLawyer

# - type: playTimeTracker
  # id: JobLibrarian

# - type: playTimeTracker
  # id: JobMedicalDoctor

# - type: playTimeTracker
  # id: JobMedicalIntern

# - type: playTimeTracker
  # id: JobMime

# - type: playTimeTracker
  # id: JobMusician

# - type: playTimeTracker
  # id: JobPassenger

# - type: playTimeTracker
  # id: JobParamedic

# - type: playTimeTracker
  # id: JobPsychologist

# - type: playTimeTracker
  # id: JobQuartermaster

# - type: playTimeTracker
  # id: JobReporter

# - type: playTimeTracker
  # id: JobResearchAssistant

# - type: playTimeTracker
  # id: JobResearchDirector

# - type: playTimeTracker
  # id: JobSalvageSpecialist

# - type: playTimeTracker
  # id: JobScientist

# - type: playTimeTracker
  # id: JobSecurityCadet

# - type: playTimeTracker
  # id: JobSecurityOfficer

# - type: playTimeTracker
  # id: JobSeniorEngineer

# - type: playTimeTracker
  # id: JobSeniorOfficer

# - type: playTimeTracker
  # id: JobSeniorPhysician

# - type: playTimeTracker
  # id: JobSeniorResearcher

# - type: playTimeTracker
  # id: JobServiceWorker

# - type: playTimeTracker
  # id: JobStationEngineer

# - type: playTimeTracker
  # id: JobTechnicalAssistant

# - type: playTimeTracker
  # id: JobWarden

# - type: playTimeTracker
  # id: JobBoxer

# - type: playTimeTracker
  # id: JobZookeeper
