- type: job
  id: MilitaryScientist
  name: job-name-militaryscientist
  description: job-description-militaryscientist
  playTimeTracker: JobMilitaryScientist
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: MilitaryScientistGear
  icon: "JobIconMilitaryScientist"
  supervisors: job-supervisors-head-operations
  canBeAntag: false
  access:
    - Research
    - Maintenance
    - Medical
    - Chemistry

- type: startingGear
  id: MilitaryScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryScientist
    back: ClothingBackpackScience
    eyes: ClothingEyesGlassesMeson
    id: MilitaryScientistIDCard
    ears: ClothingHeadsetAltScience
    belt: ClothingBeltUtilityEngineering
    shoes: ClothingShoesColorBrown
