- type: job
  id: Rigger
  name: job-name-rigger
  description: job-description-rigger
  playTimeTracker: JobRigger
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: RiggerGear
  icon: "JobIconRigger"
  supervisors: job-supervisors-supply-officer
  canBeAntag: false
  access:
    - Cargo

- type: startingGear
  id: RiggerGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    id: RiggerIDCard
