[game]
hostname = "🛰️ Corvax — Colonial Marines 🦂 [ЗБТ]"
desc = "Colonial Marines первый русскоязычный проект в Space Station 14.\nНа Colonial Marines средние требования к RP."
maxplayers = 120
soft_max_players = 100
map_rotation = true
lobbyduration = 360
fallbackpreset = "extended"
lobbyenabled = true
role_timers = true
artifact_round_end_timer = 0.0

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
map_enabled = true
preset_enabled = false

[server]
rules_header = "ui-rules-header-corvax" # UPDATE
rules_file = "RulesCorvax.txt" # UPDATE

[discord]
rich_main_icon_id = "corvax" # UPDATE

[rules]
time = 1.0

[viewport]
maximum_width = 26

[infolinks]
discord = "https://discord.gg/QBCV2f42xG"
wiki = "https://station14.ru/wiki/Колониальные_Морпехи"
patreon = "https://boosty.to/corvax"
appeal = "https://discord.gg/QBCV2f42xG"

[hub]
tags = "lang:ru,rp:med,region:eu_e"
