- type: job
  id: AlfaMedic
  name: job-name-alfa-medic
  description: job-description-alfamedic
  playTimeTracker: JobAlfaMedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobAlfaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobDeltaMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobBravoMarine
      time: 0
    - !type:RoleTimeRequirement
      role: JobCharlieMarine
      time: 0
  startingGear: AlfaMedicGear
  icon: "JobIconAlfaMedic"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
    - SquadAlphaMedic

- type: startingGear
  id: AlfaMedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAlpha_med
    id: AMedicIDCard
    ears: ClothingHeadsetMarineAlfa
